var DATA_KEY = 'fabui.fabgrid';
var EVENT_NAMESPACE = '.fabgrid';
var GRID_EVENTS = [
  'autoGeneratedColumns',
  'autoSizedColumn',
  'autoSizedRow',
  'autoSizingColumn',
  'autoSizingRow',
  'beforeLoad',
  'beginningEdit',
  'bigCheckboxesChanged',
  'cellCopied',
  'cellEditStarting',
  'cellEditEnding',
  'cellEditEnded',
  'columnGroupCollapsedChanged',
  'columnGroupCollapsedChanging',
  'columnVisibilityChanged',
  'copied',
  'copiedCell',
  'copyFailed',
  'copying',
  'copyingCell',
  'deletedRow',
  'deletingRow',
  'draggedColumn',
  'draggedRow',
  'draggingColumn',
  'draggingRow',
  'filterChanged',
  'excelExported',
  'excelExportFailed',
  'excelExporting',
  'formatItem',
  'groupCollapsedChanged',
  'groupCollapsedChanging',
  'itemsSourceChanged',
  'itemsSourceChanging',
  'loadedRows',
  'loadingRows',
  'loadError',
  'loadSuccess',
  'pageChanged',
  'pageChanging',
  'pasted',
  'pastedCell',
  'pasting',
  'pastingCell',
  'prepareCellForEdit',
  'refreshed',
  'refreshing',
  'resizedColumn',
  'resizedRow',
  'resizingColumn',
  'resizingRow',
  'rowAdded',
  'rowEditEnded',
  'rowEditEnding',
  'rowEditStarted',
  'rowEditStarting',
  'rowSelectionChanged',
  'rowSelectionChanging',
  'rowHeaderModeChanged',
  'scrollPositionChanged',
  'searchCleared',
  'searchRowVisibilityChanged',
  'selectionChanged',
  'selectionChanging',
  'sortedColumn',
  'sortingColumn',
  'updatedLayout',
  'updatedView',
  'updatingLayout',
  'updatingView',
  'viewportChanged'
];

var SETTER_METHODS = {
  activeCellBorder: 'setActiveCellBorder',
  allowFiltering: 'setAllowFiltering',
  columns: 'setColumns',
  editMode: 'setEditMode',
  frozenColumns: 'setFrozenColumns',
  frozenRightColumns: 'setFrozenRightColumns',
  headerDisplayMode: 'setHeaderDisplayMode',
  itemsSource: 'setItemsSource',
  locale: 'setLocale',
  multiSelectRows: 'setMultiSelectRows',
  pageNumber: 'setPage',
  pageSize: 'setPageSize',
  rowHeaderWidth: 'setRowHeaderWidth',
  rowGroups: 'setRowGroups',
  showFooter: 'setShowFooter',
  showRowHeaders: 'setShowRowHeaders',
  showSearchRow: 'setShowSearchRow'
};

export function toJQueryEventName(value) {
  return String(value || '').toLowerCase();
}

export function isPublicMethod(instance, name) {
  return Boolean(instance && typeof name === 'string' && name.charAt(0) !== '_' && typeof instance[name] === 'function');
}

export function createFabGridJQuery($, fabui) {
  if (!$ || !$.fn) throw new Error('fabgrid-jquery requires jQuery.');
  if (!fabui || typeof fabui.FabGrid !== 'function') throw new Error('fabgrid-jquery requires fabui.FabGrid.');
  function getInstance(element) {
    return $.data(element, DATA_KEY);
  }

  function setInstance(element, instance) {
    $.data(element, DATA_KEY, instance);
  }

  function removeInstance(element) {
    $.removeData(element, DATA_KEY);
  }

  function triggerLifecycle(element, name, instance) {
    $(element).triggerHandler(name + EVENT_NAMESPACE, [instance]);
  }

  function unbindCoreEvents(instance) {
    var bindings = instance.__fabgridJQueryBindings || [];
    bindings.forEach(function(binding) {
      if (binding.event && typeof binding.event.removeHandler === 'function') {
        binding.event.removeHandler(binding.handler, instance);
      } else if (binding.name && typeof instance.off === 'function') {
        instance.off(binding.name, binding.handler);
      }
    });
    delete instance.__fabgridJQueryBindings;
    delete instance.__fabgridJQueryCallbacks;
  }

  function updateEventCallbacks(instance, options) {
    var callbacks = instance.__fabgridJQueryCallbacks || {};
    GRID_EVENTS.forEach(function(name) {
      if (Object.prototype.hasOwnProperty.call(options || {}, name)) {
        callbacks[name] = options[name];
      }
    });
    instance.__fabgridJQueryCallbacks = callbacks;
  }

  function bindCoreEvents(element, instance) {
    var bindings = [];
    GRID_EVENTS.forEach(function(name) {
      var coreEvent = instance[name];
      var handler;
      var forward = function(args) {
        var event = $.Event(toJQueryEventName(name) + EVENT_NAMESPACE);
        var callback = instance.__fabgridJQueryCallbacks[name];
        args = args || {};
        $(element).triggerHandler(event, [args, instance]);
        if (typeof callback === 'function' && callback.call(element, event, args, instance) === false) {
          args.cancel = true;
        }
        if (event.isDefaultPrevented && event.isDefaultPrevented()) args.cancel = true;
        return args.cancel !== true;
      };
      if (coreEvent && typeof coreEvent.addHandler === 'function') {
        handler = function(sender, args) {
          return forward(args);
        };
        coreEvent.addHandler(handler, instance);
        bindings.push({ event: coreEvent, handler: handler });
      } else if (typeof instance.on === 'function' && typeof instance.off === 'function') {
        handler = function(args) {
          return forward(args);
        };
        instance.on(name, handler);
        bindings.push({ name: name, handler: handler });
      }
    });
    instance.__fabgridJQueryBindings = bindings;
  }

  function setOption(instance, name, value) {
    var setter = SETTER_METHODS[name];
    if (setter && typeof instance[setter] === 'function') {
      instance[setter](value);
      return;
    }
    if (name in instance && typeof instance[name] !== 'function') {
      instance[name] = value;
      return;
    }
    instance.options[name] = value;
    if (typeof instance.invalidate === 'function') instance.invalidate();
  }

  function setOptions(instance, options) {
    updateEventCallbacks(instance, options || {});
    Object.keys(options || {}).forEach(function(name) {
      if (GRID_EVENTS.indexOf(name) >= 0) return;
      setOption(instance, name, options[name]);
    });
  }

  function getOption(instance, name) {
    if (name in instance && typeof instance[name] !== 'function') return instance[name];
    return instance.options ? instance.options[name] : undefined;
  }

  function create(element, options) {
    var instance = new fabui.FabGrid(element, options || {});
    setInstance(element, instance);
    updateEventCallbacks(instance, options || {});
    bindCoreEvents(element, instance);
    triggerLifecycle(element, 'initialized', instance);
    return instance;
  }

  function destroy(element, instance) {
    if (!instance) return;
    unbindCoreEvents(instance);
    if (typeof instance.dispose === 'function') instance.dispose();
    removeInstance(element);
    triggerLifecycle(element, 'destroyed', instance);
  }

  function plugin(command) {
    var args = Array.prototype.slice.call(arguments, 1);
    var first = this[0];
    var instance;
    var result;

    if (typeof command !== 'string') {
      return this.each(function() {
        var current = getInstance(this);
        if (current) setOptions(current, command || {});
        else create(this, command || {});
      });
    }

    if (command === 'instance') return first ? getInstance(first) : undefined;
    if (command === 'option' && args.length === 1 && typeof args[0] === 'string') {
      instance = first ? getInstance(first) : null;
      return instance ? getOption(instance, args[0]) : undefined;
    }

    this.each(function() {
      var current = getInstance(this);
      if (!current) throw new Error('Cannot call fabgrid method before initialization: ' + command);
      if (command === 'destroy') {
        destroy(this, current);
        return;
      }
      if (command === 'option') {
        if (typeof args[0] === 'string') setOption(current, args[0], args[1]);
        else setOptions(current, args[0] || {});
        return;
      }
      if (!isPublicMethod(current, command)) throw new Error('Unknown or private fabgrid method: ' + command);
      result = current[command].apply(current, args);
    });

    return result === undefined ? this : result;
  }

  $.fn.fabgrid = plugin;

  function registerPivotPlugin(pluginName, constructorName) {
    var dataKey = 'fabui.' + pluginName;
    var namespace = '.' + pluginName;

    function getPivotInstance(element) {
      return $.data(element, dataKey);
    }

    function setPivotOption(instance, name, value) {
      if ((name === 'engine' || name === 'itemsSource') && value instanceof fabui.pivot.PivotEngine) {
        if (constructorName === 'PivotGrid') instance.setPivotEngine(value);
        else if (constructorName === 'PivotWorkspace') instance.setEngine(value);
        else instance.setItemsSource(value);
        return;
      }
      if (name === 'itemsSource' && constructorName === 'PivotWorkspace' && Array.isArray(value)) {
        instance.setItemsSource(value);
        return;
      }
      if (name === 'locale' && typeof instance.setLocale === 'function') {
        instance.setLocale(value);
        return;
      }
      if (name === 'field' && constructorName === 'PivotSlicer') {
        instance.setField(value);
        return;
      }
      if (name in instance && typeof instance[name] !== 'function') {
        instance[name] = value;
        return;
      }
      instance.options = instance.options || {};
      instance.options[name] = value;
      if (typeof instance.refresh === 'function') instance.refresh();
    }

    function createPivot(element, options) {
      var Constructor = fabui.pivot[constructorName];
      var instance = new Constructor(element, options || {});
      $.data(element, dataKey, instance);
      $(element).triggerHandler('initialized' + namespace, [instance]);
      return instance;
    }

    function destroyPivot(element, instance) {
      if (!instance) return;
      if (typeof instance.dispose === 'function') instance.dispose();
      $.removeData(element, dataKey);
      $(element).triggerHandler('destroyed' + namespace, [instance]);
    }

    function pivotPlugin(command) {
      var args = Array.prototype.slice.call(arguments, 1);
      var first = this[0];
      var result;
      if (typeof command !== 'string') {
        return this.each(function() {
          var current = getPivotInstance(this);
          if (!current) {
            createPivot(this, command || {});
            return;
          }
          Object.keys(command || {}).forEach(function(name) {
            setPivotOption(current, name, command[name]);
          });
        });
      }
      if (command === 'instance') return first ? getPivotInstance(first) : undefined;
      if (command === 'option' && args.length === 1 && typeof args[0] === 'string') {
        var instance = first ? getPivotInstance(first) : null;
        return instance ? instance[args[0]] : undefined;
      }
      this.each(function() {
        var current = getPivotInstance(this);
        if (!current) throw new Error('Cannot call ' + pluginName + ' method before initialization: ' + command);
        if (command === 'destroy') {
          destroyPivot(this, current);
        } else if (command === 'option') {
          if (typeof args[0] === 'string') setPivotOption(current, args[0], args[1]);
          else Object.keys(args[0] || {}).forEach(function(name) {
            setPivotOption(current, name, args[0][name]);
          });
        } else {
          if (!isPublicMethod(current, command)) {
            throw new Error('Unknown or private ' + pluginName + ' method: ' + command);
          }
          result = current[command].apply(current, args);
        }
      });
      return result === undefined ? this : result;
    }

    $.fn[pluginName] = pivotPlugin;
    return {
      dataKey: dataKey,
      eventNamespace: namespace,
      getInstance: getPivotInstance,
      destroy: function(element) { destroyPivot(element, getPivotInstance(element)); }
    };
  }

  var pivotPlugins = {
    panel: registerPivotPlugin('fabpivotpanel', 'PivotPanel'),
    grid: registerPivotPlugin('fabpivotgrid', 'PivotGrid'),
    chart: registerPivotPlugin('fabpivotchart', 'PivotChart'),
    workspace: registerPivotPlugin('fabpivotworkspace', 'PivotWorkspace'),
    slicer: registerPivotPlugin('fabpivotslicer', 'PivotSlicer')
  };

  return {
    dataKey: DATA_KEY,
    eventNamespace: EVENT_NAMESPACE,
    getInstance: getInstance,
    destroy: function(element) { destroy(element, getInstance(element)); },
    pivot: pivotPlugins
  };
}

export default createFabGridJQuery;
